version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-personal-landing
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
    restart: always
    ports:
      - 8080:80
      - 443:443
