version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-personal-landing
    restart: always
    environment:
      - MYSQL_DATABASE=personal-landing
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  nginx:
    image: nginx:latest
    container_name: nginx-personal-landing
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    restart: always
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - php
  php:
    image: php:7.2-fpm
    container_name: php-personal-landing
    restart: always
    volumes:
      - ./src:/var/www
    ports:
      - 9000:9000