version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Decrypt files if branch is master
          command: |
            if [ ${CIRCLE_BRANCH} == "master" ]; then
              sh ./.circleci/decrypt-files.sh
            fi
      - run:
          name: Deploy to S3 if branch is master
          command: |
            if [ ${CIRCLE_BRANCH} == "master" ]; then
              sh ./.circleci/deploy.sh
            fi
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
